devlop_env:
  stage: PORD

databaes:
  100DBS:100dbs
  200DBS:200dbs

credentials:
  ora01_user: xxxxx
  ora01.pssswd: xxxxx
  ora02.user: xxxxx
  ora02.pssswd: xxxxx

tns_names:
  # Debezium 커네터가 접속할 URL은 oci로 접속해야 함(xstream 요구사항)
  tns_oci_0001dbs: jdbc:oracle:oci@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=[IP])(PORT=[Port No]))(ADDRESS=(PROTOCOL=TCP)(HOST=[IP])(PORT=[Port No]))(FAILOVER=ON)(LOAD_BALANCE=OFF)(CONNECT_DATA=(SERVICE_NAME=[Service Name])(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
  tns_oci_0003dbs: jdbc:oracle:oci@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=[IP])(PORT=[Port No]))(ADDRESS=(PROTOCOL=TCP)(HOST=[IP])(PORT=[Port No]))(ADDRESS=(PROTOCOL=TCP)(HOST=[IP])(PORT=[Port No]))(FAILOVER=ON)(LOAD_BALANCE=OFF))(CONNECT_DATA=(SERVICE_NAME=[Service Name])(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
  tns_oci_0003dbs: jdbc:postgresql://[IP]/xxxx_main
  
  # Conflunet 커네터가 접속할 URL은 thin로 접속해야 함
  tns_thin_0001dbs: jdbc:oracle:thin@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=[IP])(PORT=[Port No]))(ADDRESS=(PROTOCOL=TCP)(HOST=[IP])(PORT=[Port No]))(FAILOVER=ON)(LOAD_BALANCE=OFF)(CONNECT_DATA=(SERVICE_NAME=[Service Name])(FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC))))
  tns_thin_0001dbs: jdbc:postgresql://[IP]/xxxx_main

ip_addresses:
  ip_001db: xxx.xxx.xxx.xxx

bootstrap-servers: 
  broker: kakfa01:6667,kakfa02:6667,kakfa03:6667

xstream:
  xstr_srv_nm: prdbspark

topic-prefixes:
  topic-prefix-oggbd-xxx01: DEV.CONNECT.XXXDBS_01
  topic-prefix-oggbd-xxx02: DEV.CONNECT.XXXDBS_02
  topic-prefix-debezium-xxx03: DEV.CONNECT.XXXDBS_03
  topic-prefix-spark_xxxdb: DEV.CONNECT.XXXDBS
